#!/usr/bin/bash
# memo2html -- Samsung memo to html conversion script
# saves typing a series of commands
source $HOME/.config/memo2html.cfg
m=$(basename $1)
MEMO=${m%%.*}
MF=$MEMOS/$MEMO
mkdir -p $MF
unzip -qq -o $1 -d $MF
cd $MF
xsltproc -o index.html $PREFIX/share/memo2html.xsl memo_content.xml
sed -i -e 's|src=\"/|src=\"|g' index.html
exit 0

